using System.Web;
using System.Web.Optimization;

namespace UI
{
    public class BundleConfig
    {
        // For more information on bundling, visit https://go.microsoft.com/fwlink/?LinkId=301862
        public static void RegisterBundles(BundleCollection bundles)
        {
            bundles.Add(new ScriptBundle("~/bundles/jquery").Include(
                        "~/Scripts/jquery-{version}.js"));

            bundles.Add(new ScriptBundle("~/bundles/jqueryval").Include(
                        "~/Scripts/jquery.validate*"));

            // Use the development version of Modernizr to develop with and learn from. Then, when you're
            // ready for production, use the build tool at https://modernizr.com to pick only the tests you need.
            bundles.Add(new ScriptBundle("~/bundles/modernizr").Include(
                        "~/Scripts/modernizr-*"));

            bundles.Add(new ScriptBundle("~/bundles/bootstrap").Include(
                      "~/Scripts/bootstrap.js"));

            bundles.Add(new StyleBundle("~/Content/css").Include(
                      "~/Content/bootstrap.css",
                      "~/Content/Site.css"));

            bundles.Add(new ScriptBundle("~/bundles/general-config").Include(
                            "~/Scripts/AutoGenerated/GeneralConfig/general-config-controller.js"));

            bundles.Add(new ScriptBundle("~/bundles/book").Include(
                      "~/node_modules/select2/dist/js/select2.min.js",
                      "~/node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js",
                      "~/Scripts/AutoGenerated/Book/book-controller.js"));

            bundles.Add(new StyleBundle("~/book/css").Include(
                      "~/node_modules/select2/dist/css/select2.min.css",
                      "~/node_modules/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css"));

            bundles.Add(new ScriptBundle("~/bundles/datatables").Include(
                      "~/node_modules/datatables.net/js/jquery.dataTables.min.js",
                      "~/node_modules/datatables.net-bs/js/dataTables.bootstrap.min.js"));

            bundles.Add(new StyleBundle("~/datatables/css").Include(
                      "~/node_modules/datatables.net-bs/css/dataTables.bootstrap.min.css"));

            bundles.Add(new ScriptBundle("~/bundles/books").Include(
                      "~/node_modules/moment/min/moment.min.js",
                      "~/Scripts/AutoGenerated/DT/base-dt-controller.js",
                      "~/Scripts/AutoGenerated/DT/book-dt-controller.js"));

            bundles.Add(new ScriptBundle("~/bundles/authors").Include(
                      "~/Scripts/AutoGenerated/DT/base-dt-controller.js",
                      "~/Scripts/AutoGenerated/DT/author-dt-controller.js"));

            bundles.Add(new ScriptBundle("~/bundles/popup")
                        .IncludeDirectory("~/Scripts/AutoGenerated/Popup", "*.js", true));

            bundles.Add(new ScriptBundle("~/bundles/delete")
                    .IncludeDirectory("~/Scripts/AutoGenerated/Delete", "*.js", true));

            bundles.Add(new ScriptBundle("~/bundles/alert")
                    .IncludeDirectory("~/Scripts/AutoGenerated/Alert", "*.js",true));

            bundles.Add(new ScriptBundle("~/bundles/save").Include(
                      "~/Scripts/AutoGenerated/Save/save-base-controller.js",
                      "~/Scripts/AutoGenerated/Save/save-business.js",
                      "~/Scripts/AutoGenerated/Save/save-service.js"));

            bundles.Add(new ScriptBundle("~/bundles/save-author").Include(
                      "~/Scripts/AutoGenerated/Save/save-author-controller.js"));

            bundles.Add(new ScriptBundle("~/bundles/save-book").Include(
                      "~/Scripts/AutoGenerated/Save/save-book-controller.js"));

            bundles.Add(new ScriptBundle("~/bundles/view-models").Include(
                      "~/Scripts/AutoGenerated/ViewModels/alertVM.js",
                      "~/Scripts/AutoGenerated/ViewModels/baseVM.js",
                      "~/Scripts/AutoGenerated/ViewModels/popupVM.js",
                      "~/Scripts/AutoGenerated/ViewModels/authorBaseVM.js",
                      "~/Scripts/AutoGenerated/ViewModels/bookBaseVM.js",
                      "~/Scripts/AutoGenerated/ViewModels/authorVM.js",
                      "~/Scripts/AutoGenerated/ViewModels/bookVM.js",
                      "~/Scripts/AutoGenerated/ViewModels/authorVM.js",
                      "~/Scripts/AutoGenerated/ViewModels/bookEditVM.js",
                      "~/Scripts/AutoGenerated/ViewModels/urlsDT.js",
                      "~/Scripts/AutoGenerated/ViewModels/bookUrlsDT.js"));
        }
    }
}
