CREATE PROCEDURE [dbo].[USPBookDelete]
	@Id int
AS
	BEGIN TRY
		BEGIN TRANSACTION

			DELETE FROM AuthorBook WHERE BookId = @Id;
			DELETE FROM Book WHERE Id = @Id;

		COMMIT TRANSACTION
	
	END TRY
	BEGIN CATCH

		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION

		DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE()
        DECLARE @ErrorSeverity INT = ERROR_SEVERITY()
        DECLARE @ErrorState INT = ERROR_STATE()

		RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);

	END CATCH

RETURN 0